---
title: "05_GeneMANIA_validation"
author: "Tabea M. Soelter"
date: '2023-08-08'
output: html_document
---
docker 1.0.4.

# Start-up
```{r}
library(tidyverse)
library(igraph)
library(here)
library(biomaRt)
```

# load data
```{r}
prior <- read_delim(here(
  "data",
  "ccc",
  "gene_mania_prior",
  "COMBINED.DEFAULT_NETWORKS.BP_COMBINING.txt"))

meta <- read_delim(here(
  "data",
  "ccc",
  "gene_mania_prior",
  "COMBINATION_WEIGHTS.DEFAULT_NETWORKS.BP_COMBINING.txt"))
```
```{r}
uniprot_ids <- as.vector(c(prior$Gene_A, prior$Gene_B)) %>% unique()

length(uniprot_ids) # 19680

ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")

gene_names <- getBM(attributes = c("uniprotswissprot", "hgnc_symbol"),
                    filters = "uniprotswissprot", 
                    values = uniprot_ids, 
                    mart = ensembl)

length(gene_names$uniprotswissprot) # 18672

prior_mapped <- prior %>%
  mutate(Gene_A_hgnc = ifelse(any(Gene_A == gene_names$uniprotswissprot), gene_names$hgnc_symbol, NA))



prior_mapped <- prior %>%
  left_join(gene_names, by = c("Gene_A" = "uniprotswissprot")) %>%
  mutate(gene_a_hgnc = hgnc_symbol) %>%
  dplyr::select(-hgnc_symbol) %>%
  left_join(gene_names, by = c("Gene_B" = "uniprotswissprot")) %>%
  mutate(gene_b_hgnc = hgnc_symbol) %>%
  dplyr::select(gene_a_hgnc, gene_b_hgnc, Weight)

# igraph 
igraph_object <- graph.data.frame(prior_mapped, directed = FALSE)

# set edge weights
E(igraph_object)$weight <- prior_mapped$Weight

dist_matrix <- distances(igraph_object,
                         v = V(igraph_object),
                         to = V(igraph_object),
                         algorithm = "unweighted")

colnames(dist_matrix)
rownames(dist_matrix)
```

Need to somehow subset and see how close 2 groups of target genes from same ligand-receptor are from each other.
- permutation testing here? see if they are closer than groups of genes by chance?




