---
title: "02_figure_2"
author: "Tabea M. Soelter"
date: '2023-05-19'
output: html_document
---
Code for figure 2

# packages
```{r}
library(tidyverse)
library(ComplexHeatmap)
library(Seurat)
```

# data
```{r}
ex_prioritization_tables <- readRDS("/data/user/tsoelter/projects/230313_TS_CCCinHumanAD/results/intermediate_outputs/geo/ccc/ex_prioritization_tables.rds")

in_prioritization_tables <- readRDS("/data/user/tsoelter/projects/230313_TS_CCCinHumanAD/results/intermediate_outputs/geo/ccc/in_prioritization_tables.rds")

geo_object <- readRDS("/data/user/tsoelter/projects/230313_TS_CCCinHumanAD/data/geo_processed_seurat.rds")
```

# prep plot
- get ligands 
- get gex of ligands from seurat object
```{r}
gene_matrix <- GetAssayData(geo_object, assay = "RNA")


ex_ligands <- ex_prioritization_tables$prioritization_tbl_ligand_target %>% select(ligand) %>% unique()
ex_ligands <- ex_ligands$ligand

gex <- gene_matrix[ex_ligands, ]


metadata <- geo_object[[]]
metadata <- metadata[rownames(metadata) %in% colnames(gex), ]

```

```{r}
metadata <- geo_object@meta.data

metadata <- metadata %>% mutate(cell_type = recode(RNA_snn_res.0.5,
  `1`  = "Oligodendrocytes",
  `2`  = "Oligodendrocytes",
  `3`  = "Oligodendrocytes",
  `4`  = "Astrocytes",
  `5`  = "Microglia",
  `6`  = "Excitatory Neurons",
  `7`  = "OPCs",
  `8`  = "Inhibitory Neurons",
  `9`  = "Excitatory Neurons",
  `10` = "Inhibitory Neurons",
  `11` = "Inhibitory Neurons",
  `12` = "Astrocytes",
  `13` = "Inhibitory Neurons",
  `14` = "Excitatory Neurons",
  `15` = "Excitatory Neurons",
  `16` = "Inhibitory Neurons",
  `17` = "Excitatory Neurons",
  `18` = "Microglia",
  `19` = "OPCs",
  `20` = "Oligodendrocytes",
  `21` = "Endothelial Cells",
  `22` = "Microglia",
  `23` = "Unknown"))

ordered_metadata <- metadata[order(metadata$cell_type), ]

ha <- HeatmapAnnotation(df = ordered_metadata,
                        show_annotation_name = TRUE)


# Expression data


seurat_object <- ScaleData(geo_object,
                           features = ex_ligands)

my_data <- seurat_object@assays$RNA@scale.data

gene_data <- subset(my_data, rownames(my_data) %in% ex_ligands)

data <- gene_data[, rownames(ordered_metadata)]

p <- Heatmap(data)
draw(p)
```


```{r}
counts <- GetAssayData(geo_object, assay = "RNA", slot = "data")
counts <- as.matrix(counts[rownames(counts) %in% ex_ligands, ])

metadata <- geo_object[[]]
metadata <- metadata[rownames(metadata) %in% colnames(counts), ]

metadata <- metadata %>% mutate(cell_type = recode(RNA_snn_res.0.5,
  `1`  = "Oligodendrocytes",
  `2`  = "Oligodendrocytes",
  `3`  = "Oligodendrocytes",
  `4`  = "Astrocytes",
  `5`  = "Microglia",
  `6`  = "Excitatory Neurons",
  `7`  = "OPCs",
  `8`  = "Inhibitory Neurons",
  `9`  = "Excitatory Neurons",
  `10` = "Inhibitory Neurons",
  `11` = "Inhibitory Neurons",
  `12` = "Astrocytes",
  `13` = "Inhibitory Neurons",
  `14` = "Excitatory Neurons",
  `15` = "Excitatory Neurons",
  `16` = "Inhibitory Neurons",
  `17` = "Excitatory Neurons",
  `18` = "Microglia",
  `19` = "OPCs",
  `20` = "Oligodendrocytes",
  `21` = "Endothelial Cells",
  `22` = "Microglia",
  `23` = "Unknown"))

ordered_metadata <- metadata[order(metadata$cell_type), ]

ha <- HeatmapAnnotation(df = ordered_metadata,
                        show_annotation_name = TRUE)

genes_mat <- subset(counts, rownames(counts) %in% ex_ligands)

genes_mat_o <- genes_mat[, rownames(ordered_metadata)]

p <- Heatmap(
  genes_mat,
  #width = unit(15, "cm"), 
  #height = unit(25, "cm"),
  row_names_side = "left",
  #col = col_fun,
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  column_order = NULL,
  show_row_dend = FALSE,
  show_column_dend = FALSE,
  show_row_names = TRUE,
  row_names_gp = gpar(fontsize = 8),
  show_column_names = FALSE,
  use_raster = TRUE,
  raster_device = c("png"),
  #raster_quality = 15,
  bottom_annotation = NULL,
  #top_annotation = ha
)

draw(p)
```

### For loop to generate combined DEG output at log2FC threshold of 0.1:
```{r}


# specify the cell types in the data to loop through
celltypes <- levels(geo_object)

# create empty dataframe to store the loop outputs within
DEGs_df <- data.frame()

# for loop, loops through each of the 'celltypes' in cerebral and calculates the DEG between conditions (heterozygous and control)
for (i in celltypes) {
  # subset seurat data for each cerebral cell type ----------
  celltype <- subset(geo_object, idents = i)
  # change the subsetted object identity to be type (heterozygous or control) so that DEG are calculated between the two conditions ------------
  Idents(celltype) <- celltype@meta.data$orig.ident
  # calculate DEGs between conditions -----------
  DEGs <- FindAllMarkers(celltype,
    logfc.threshold = 0.1,
    test.use = "wilcox",
    only.pos = FALSE,
    assay = "RNA"
  )
  # add an additional column to the df with cell type annotation (for downstream analysis purposes) -----------
  DEGs$cell_type <- i
  # combine the dataframe generated in the for loop with the entire list of all DEGs across cell types in cerebral ----------
  DEGs_df <- rbind(DEGs_df, DEGs)
}


# filter DEG list for just setbp1 targets
subset <- DEGs_df[DEGs_df$gene %in% ex_ligands, ]

# grab just log2fc values from DEG matrix, keep rownames and then order (below) by rowname
genes_mat <- subset[, c("avg_log2FC", "cell_type", "gene", "cluster", "p_val_adj"), drop = FALSE]

# filtering for significant values
genes_mat <- genes_mat[genes_mat$p_val_adj < 0.5, ]
genes_mat <- genes_mat[, -5]

genes_pivot <- pivot_wider(genes_mat, names_from = c("cell_type", "cluster"), values_from = "avg_log2FC", names_repair = "minimal")
genes_pivot[is.na(genes_pivot)] <- 0
rownames <- genes_pivot$gene # add gene names as rownames
genes_pivot <- genes_pivot[, -1, drop = FALSE] # drop gene column
rownames(genes_pivot) <- rownames

# grab meta data for plot:
meta <- as.data.frame(colnames(genes_pivot))
meta.data <- t(as.data.frame(strsplit(sub("(_)(?=[^_]+$)", " ", meta$`colnames(genes_pivot)`, perl = TRUE), " ")))

meta.data <- t(genes_pivot) %>% as.data.frame()

rownames(meta.data) <- meta$`colnames(genes_pivot)`
colnames(meta.data) <- c("cell_type", "condition")

heatmap(genes_pivot %>% as.matrix())

```


# plots
```{r}

```

