---
title: "03_Figure_3"
author: "Tabea M. Soelter"
date: '2023-08-11'
output: html_document
---
```{r}
library(tidyverse)
library(multinichenetr)
library(ggalluvial)
library(here)
```

# colors
```{r}
colors <- c(
  `Oligodendrocytes` = "royalblue4",
  `Microglia` = "orchid3",
  `OPCs` = "mediumpurple1",
  `Astrocytes` = "cornflowerblue",
  `Excitatory Neurons` = "slateblue3",
  `Inhibitory Neurons` = "darkslategray3",
  `Pericytes` = "deepskyblue3",
  `Endothelial cells` = "darkolivegreen4")
```


```{r}
geo_ccc <- lr_target_prior_cor_filtered_geo %>%
  dplyr::select(sender, receiver, ligand, target, receptor, id) %>%
  filter(id %in% i4) %>%
  mutate(origin = "geo")

gse_ccc <- lr_target_prior_cor_filtered_gse %>%
  dplyr::select(sender, receiver, ligand, target, receptor, id) %>%
  filter(id %in% i4) %>%
  mutate(origin = "gse")

ccc_combined <- rbind(geo_ccc, gse_ccc) %>%
  select(sender, receiver, ligand, receptor, id) %>%
  unique()

ccc_in <- ccc_combined %>%
  filter(receiver == "Inhibitory Neurons")

ccc_ex <- ccc_combined %>%
  filter(receiver == "Excitatory Neurons")


ggplot(ccc_combined,
       aes(axis1 = ligand, axis2 = receptor, axis3 = target)) +
  geom_alluvium(aes(fill = sender)) +
  geom_stratum(aes(fill = receiver)) +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  theme_bw()


ggplot(ccc_ex,
       aes(axis1 = ligand, axis2 = receptor, axis3 = target)) +
  geom_alluvium(aes(fill = sender)) +
  geom_stratum(aes(fill = sender)) +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  theme_bw()

ggplot(ccc_in,
       aes(axis1 = ligand, axis2 = receptor, axis3 = target)) +
  geom_alluvium(aes(fill = sender)) +
  geom_stratum(aes(fill = sender)) +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  theme_bw()

ggplot(ccc_combined,
       aes(axis1 = receptor, axis2 = target, order = receiver)) +
  geom_alluvium(aes(fill = receiver, order = receiver)) +
  geom_stratum(aes(fill = receiver)) +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  theme_void()
```

###### FINAL FIGURE CODE
```{r}
ccc_combined1 <- ccc_combined
ccc_combined1$ligand <- factor(ccc_combined1$ligand, levels = as.character(unique(ccc_combined1$ligand)))
ccc_combined1$receptor <- factor(ccc_combined1$receptor, levels = as.character(unique(ccc_combined1$receptor)))

ccc_combined1 <- ccc_combined1 %>% arrange(sender)


## FINAL
ggplot(ccc_combined1, aes(axis1 = ligand, axis2 = receptor), label = stratum) +
  scale_x_discrete(limits = c("Ligand", "Receptor")) + 
  xlab("Type") +
  geom_alluvium() +
  stat_alluvium(lode.guidance = "frontback") +
  geom_stratum(aes(fill = sender)) +
  #geom_label(stat = "stratum", fill = "white", aes(label = after_stat(stratum))) +
  geom_flow(aes(fill = sender), stat = "alluvium", color = "black") +
  scale_fill_manual(values = colors) +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("Ligand", "Receptor")) +
  theme_void() +
  theme(axis.text.x = element_text(vjust = 2),
        legend.position = c(0.9, 0.5),
        legend.margin = margin(0, 0, 0, 0))
```

```{r}
png(here("target_heatmap.png"), height = 600, width = 700)
h2
dev.off()



h1 + h2
```

# Venn Diagram (geo and gse targets)
```{r}
install.packages("ggvenn")
library(ggvenn)

comparison_list <-
      list("geo" = geo_targets, "gse" = gse_targets)
    # create venn diagram plot
    venn <- ggvenn(comparison_list, fill_color = c("firebrick3", "goldenrod3"),
                   stroke_size = 0.7, set_name_size = 0, auto_scale = TRUE, fill_alpha = 0.7)

    
    intersect(geo_targets, gse_targets)
    
    png(here("targets_venn.png"), height = 300, width = 600)
    venn
    dev.off()
   
```

```{r}
h4
```

# compile figure
left full length = lr alluvial
right top = lrt alluvial
bottom right = venn and heatmap
```{r}
heatmap <- grid.grabExpr(draw(h2))

is.grob(heatmap)

bottom_right <- plot_grid(venn,
                          heatmap,
                          ncol = 2,
                          rel_widths = c(1, 2))
bottom_right

right <- plot_grid(lrt,
                   bottom_right,
                   ncol = 1)

right

fig3 <- plot_grid(lr,
                  right,
                  ncol = 2)

fig3
  


## attempt 2

right <- plot_grid(lrt,
                   heatmap,
                   ncol = 1)

right

fig3 <- plot_grid(lr,
                  right,
                  ncol = 2)

fig3

## atempt 3
top <- plot_grid(lr,
                 lrt,
                 ncol = 2)

bottom <- plot_grid(venn,
                    heatmap,
                    ncol = 2)

fig3 <- plot_grid(top,
                  bottom,
                  ncol = 1)

fig3

## attempt 4
h3 <-  grid.grabExpr(draw(h2,
       heatmap_legend_side = "bottom", annotation_legend_side = "bottom", merge_legend = TRUE))

left <- plot_grid(lr,
                  venn,
                  ncol = 1,
                  rel_heights = c(3,1))

right <- plot_grid(lrt,
                   h3,
                   ncol = 1)

fig3 <- plot_grid(left,
                  right,
                  ncol = 2)

png(here("test2.png"), height = 1500, width = 1200)
fig3
dev.off()
```

# panel A split into 4 attempt
```{r}
h3 <-  grid.grabExpr(draw(h2,
       heatmap_legend_side = "bottom", annotation_legend_side = "bottom", merge_legend = TRUE))


left <- ggarrange(astro,
                  micro,
                  oligo,
                  opc,
                  common.legend = T,
                  legend = "bottom")

right <- plot_grid(lrt,
                   h3,
                   ncol = 1,
                   labels = c("B", "C"),
                   rel_heights = c(2,1))

fig3_v2 <- plot_grid(left,
                     right,
                     ncol = 2,
                     rel_widths = c(2,1),
                     labels = c("A"))

fig3_v2

png(here("results", "figures", "figure4testing.png"), width = 475, height = 250, units = 'mm', res = 300)
fig3_v2
dev.off()
```


```{r}
top <- ggarrange(astro,
                  micro,
                  oligo,
                  opc,
                  common.legend = T,
                  legend = "bottom",
                 widths = c(1, -0.1, 1))

bottom <- plot_grid(lrt,
                   h3,
                   ncol = 2,
                   labels = c("B", "C"))

fig3_v3 <- plot_grid(top,
                     bottom,
                     ncol = 1,
                     labels = c("A"))
```



