---
title: "gex_ligands_receptors"
author: "Tabea M. Soelter"
date: '2023-08-28'
output: html_document
---

```{r}
library(circlize)
library(reshape2)
library(ComplexHeatmap)
library(tidyverse)
```

```{r}
geo_output <- readRDS("/data/user/tsoelter/projects/230313_TS_CCCinHumanAD/data/ccc/geo_multinichenet_output.rds")

gse_output <- readRDS("/data/user/tsoelter/projects/230313_TS_CCCinHumanAD/data/ccc/gse_multinichenet_output.rds")


receiver_oi <- c("Excitatory.Neurons", "Inhibitory.Neurons")
```

```{r}
geo_lr_info <- geo_output$prioritization_tables$group_prioritization_tbl %>%
  dplyr::filter(group == "AD", receiver %in% receiver_oi) %>%
  ungroup() %>%
  select(ligand, receptor, lfc_ligand, lfc_receptor, sender, receiver, id) %>%
  unique()  %>%
  mutate("dataset" = "geo")

gse_lr_info <- gse_output$prioritization_tables$group_prioritization_tbl %>%
  dplyr::filter(group == "AD", receiver %in% receiver_oi) %>%
  ungroup() %>%
  select(ligand, receptor, lfc_ligand, lfc_receptor, sender, receiver, id) %>%
  unique()  %>%
  mutate("dataset" = "gse")  
  
lr_info <- rbind(geo_lr_info, gse_lr_info)

lr_info$receiver <- ifelse(
  lr_info$receiver == "Inhibitory.Neurons",
  "Inhibitory Neurons",
  "Excitatory Neurons")

```

```{r}
top_n_target <- 250

group_oi = "AD"
receiver_oi = c("Excitatory.Neurons", "Inhibitory.Neurons")
sender_oi <- c("Astrocytes", "Microglia", "OPCs", "Oligodendrocytes")

contrast_tbl <- tibble(contrast = c("AD-CTRL", "CTRL-AD"),
                       group = c("AD", "CTRL"))

lr_target_prior_cor_filtered = geo_output$lr_target_prior_cor %>%
  inner_join(geo_output$ligand_activities_targets_DEgenes$ligand_activities %>%
               distinct(ligand, target, direction_regulation, contrast)) %>%
  inner_join(contrast_tbl) %>%
  filter(group == group_oi, receiver %in% receiver_oi, sender %in% sender_oi)

lr_target_prior_cor_filtered_up = lr_target_prior_cor_filtered %>%
  filter(direction_regulation == "up") %>%
  filter( (rank_of_target < top_n_target) & (pearson > 0.33 | spearman > 0.33))

lr_target_prior_cor_filtered_down = lr_target_prior_cor_filtered %>%
  filter(direction_regulation == "down") %>%
  filter( (rank_of_target < top_n_target) & (pearson < -0.33 | spearman < -0.33))

lr_target_prior_cor_filtered = bind_rows(lr_target_prior_cor_filtered_up, lr_target_prior_cor_filtered_down)

# Create new column with ligand-receptor-target only info
lr_target_prior_cor_filtered$ligand_receptor_target <- gsub("(_[^_]+_)(.*?)(_[^_]+_)",
                                                            "\\1\\4",
                                                            lr_target_prior_cor_filtered$id_target,
                                                            perl = TRUE)

# Create new column with ligand-receptor only info
lr_target_prior_cor_filtered$ligand_receptor <- gsub("^([^_]*_[^_]*).*",
                                                     "\\1",
                                                     lr_target_prior_cor_filtered$id,
                                                     perl = TRUE)

# Rename receiver cell types
lr_target_prior_cor_filtered$receiver <- ifelse(
  lr_target_prior_cor_filtered$receiver == "Inhibitory.Neurons",
  "Inhibitory Neurons",
  "Excitatory Neurons")

# Check receivers were renamed and number
table(lr_target_prior_cor_filtered$receiver) # 582 752

lr_target_prior_cor_filtered_geo <- lr_target_prior_cor_filtered

## GSE
lr_target_prior_cor_filtered = gse_output$lr_target_prior_cor %>%
  inner_join(gse_output$ligand_activities_targets_DEgenes$ligand_activities %>%
               distinct(ligand, target, direction_regulation, contrast)) %>%
  inner_join(contrast_tbl) %>%
  filter(group == group_oi, receiver %in% receiver_oi, sender %in% sender_oi)

lr_target_prior_cor_filtered_up = lr_target_prior_cor_filtered %>%
  filter(direction_regulation == "up") %>%
  filter( (rank_of_target < top_n_target) & (pearson > 0.33 | spearman > 0.33))

lr_target_prior_cor_filtered_down = lr_target_prior_cor_filtered %>%
  filter(direction_regulation == "down") %>%
  filter( (rank_of_target < top_n_target) & (pearson < -0.33 | spearman < -0.33))

lr_target_prior_cor_filtered = bind_rows(lr_target_prior_cor_filtered_up, lr_target_prior_cor_filtered_down)

# Create new column with ligand-receptor-target only info
lr_target_prior_cor_filtered$ligand_receptor_target <- gsub("(_[^_]+_)(.*?)(_[^_]+_)",
                                                            "\\1\\4",
                                                            lr_target_prior_cor_filtered$id_target,
                                                            perl = TRUE)

# Create new column with ligand-receptor only info
lr_target_prior_cor_filtered$ligand_receptor <- gsub("^([^_]*_[^_]*).*",
                                                     "\\1",
                                                     lr_target_prior_cor_filtered$id,
                                                     perl = TRUE)

# Rename receiver cell types
lr_target_prior_cor_filtered$receiver <- ifelse(
  lr_target_prior_cor_filtered$receiver == "Inhibitory.Neurons",
  "Inhibitory Neurons",
  "Excitatory Neurons")

# Check receivers were renamed and number
table(lr_target_prior_cor_filtered$receiver) # 192 378

lr_target_prior_cor_filtered_gse <- lr_target_prior_cor_filtered
```

```{r}
geo_id <- lr_target_prior_cor_filtered_geo$id %>% unique()

gse_id <- lr_target_prior_cor_filtered_gse$id %>% unique()

i4 <- intersect(geo_id, gse_id)

lr_info_filt <- lr_info %>%
  filter(id %in% i4)
```

# filter ligands for each sender
```{r}
ligands_astro <- lr_info_filt %>%
  filter(sender == "Astrocytes") %>%
  select(-sender) %>%
  unique() %>%
  select(receiver, ligand, dataset, lfc_ligand) %>%
  unique()

ligands_micro <- lr_info_filt %>%
  filter(sender == "Microglia") %>%
  select(-sender) %>%
  unique() %>%
  select(receiver, ligand, dataset, lfc_ligand) %>%
  unique()

ligands_oligo <- lr_info_filt %>%
  filter(sender == "Oligodendrocytes") %>%
  select(-sender) %>%
  select(receiver, ligand, dataset, lfc_ligand) %>%
  unique()

ligands_opcs <- lr_info_filt %>%
  filter(sender == "OPCs") %>%
  select(-sender) %>%
  select(receiver, ligand, dataset, lfc_ligand) %>%
  unique()
```

# filter receptors for each sender
```{r}
receptors_astro <- lr_info_filt %>%
  filter(sender == "Astrocytes") %>%
  select(-sender) %>%
  unique() %>%
  select(receiver, receptor, dataset, lfc_receptor) %>%
  unique()

receptors_micro <- lr_info_filt %>%
  filter(sender == "Microglia") %>%
  select(-sender) %>%
  unique() %>%
  select(receiver, receptor, dataset, lfc_receptor) %>%
  unique()

receptors_oligo <- lr_info_filt %>%
  filter(sender == "Oligodendrocytes") %>%
  select(-sender) %>%
  select(receiver, receptor, dataset, lfc_receptor) %>%
  unique()

receptors_opcs <- lr_info_filt %>%
  filter(sender == "OPCs") %>%
  select(-sender) %>%
  select(receiver, receptor, dataset, lfc_receptor) %>%
  unique()
```

# heatmap color bar
```{r}
cols <- colorRamp2(c(-1, 0, 1), c("blue", "white", "red"))
```


# astro heatmap
```{r}
astro_matrix <- dcast(ligands_astro, ligand ~ receiver + dataset, value.var = "lfc_ligand") %>%
  column_to_rownames("ligand")

astro_matrix[is.na(astro_matrix)] <- 0

# prep anno
meta <- as.data.frame(colnames(astro_matrix))
rownames(meta) <- meta$`colnames(astro_matrix)`

Receiver <- c("Excitatory.Neurons", "Excitatory.Neurons", "Inhibitory.Neurons", "Inhibitory.Neurons")
Dataset <- c("geo", "gse", "geo", "gse")
met <- cbind(Dataset, Receiver)
rownames(met) <- rownames(meta)
met <- as.data.frame(met)

anno_cols <- list("Receiver" = c("Excitatory.Neurons" = "slateblue3",
                                 "Inhibitory.Neurons" = "darkslategray3"),
                  "Dataset" = c("geo" = "firebrick3", "gse" = "goldenrod3"))

anno <- HeatmapAnnotation(df = met, show_annotation_name = FALSE, col = anno_cols,
                          annotation_legend_param = list(Dataset = list(direction = "horizontal", labels_gp = gpar(fontface = "bold")),
                                                         Receiver = list(labels = c("Excitatory Neurons", "Inhibitory Neurons"), direction = "horizontal", labels_gp = gpar(fontface = "bold"))))
                            
                          

astro_matrix <- astro_matrix[, rownames(met), drop = FALSE]

mat <- as.matrix(astro_matrix)

Heatmap(mat,
        top_annotation = anno,
        col = cols,
        show_column_names = FALSE,
        show_row_dend = TRUE,
        show_column_dend = FALSE,
        cluster_columns = FALSE,
        row_title = "Astrocyte Ligands",
        row_title_gp = gpar(fontface = "bold"),
        row_names_gp = gpar(fontface = "bold"),
        heatmap_legend_param = list(direction = "horizontal", title = "Pseudobulk Expression",
                                    labels_gp = gpar(fontface = "bold")))
```

# micro heatmap
```{r}
micro_matrix <- dcast(ligands_micro, ligand ~ receiver + dataset, value.var = "lfc_ligand") %>%
  column_to_rownames("ligand")

micro_matrix[is.na(micro_matrix)] <- 0

# prep anno
meta <- as.data.frame(colnames(micro_matrix))
rownames(meta) <- meta$`colnames(micro_matrix)`

Receiver <- c("Excitatory.Neurons", "Excitatory.Neurons", "Inhibitory.Neurons", "Inhibitory.Neurons")
Dataset <- c("geo", "gse", "geo", "gse")
met <- cbind(Dataset, Receiver)
rownames(met) <- rownames(meta)
met <- as.data.frame(met)

anno_cols <- list("Receiver" = c("Excitatory.Neurons" = "slateblue3",
                                 "Inhibitory.Neurons" = "darkslategray3"),
                  "Dataset" = c("geo" = "firebrick3", "gse" = "goldenrod3"))

anno <- HeatmapAnnotation(df = met, show_annotation_name = FALSE, col = anno_cols,
                          annotation_legend_param = list(Dataset = list(direction = "horizontal", labels_gp = gpar(fontface = "bold")),
                                                         Receiver = list(labels = c("Excitatory Neurons", "Inhibitory Neurons"), direction = "horizontal", labels_gp = gpar(fontface = "bold"))))
                            
                          

micro_matrix <- micro_matrix[, rownames(met), drop = FALSE]

mat <- as.matrix(micro_matrix)

Heatmap(mat,
        top_annotation = anno,
        col = cols,
        show_column_names = FALSE,
        show_row_dend = TRUE,
        show_column_dend = FALSE,
        cluster_columns = FALSE,
        cluster_rows = TRUE,
        row_title = "Microglia Ligands",
        row_title_gp = gpar(fontface = "bold"),
        row_names_gp = gpar(fontface = "bold"),
        heatmap_legend_param = list(direction = "horizontal", title = "Pseudobulk Expression",
                                    labels_gp = gpar(fontface = "bold")))
```

# oligo heatmap
```{r}
oligo_matrix <- dcast(ligands_oligo, ligand ~ receiver + dataset, value.var = "lfc_ligand") %>%
  column_to_rownames("ligand")

oligo_matrix[is.na(oligo_matrix)] <- 0

# prep anno
meta <- as.data.frame(colnames(oligo_matrix))
rownames(meta) <- meta$`colnames(oligo_matrix)`

Receiver <- c("Excitatory.Neurons")
Dataset <- c("geo", "gse")
met <- cbind(Dataset, Receiver)
rownames(met) <- rownames(meta)
met <- as.data.frame(met)

anno_cols <- list("Receiver" = c("Excitatory.Neurons" = "slateblue3",
                                 "Inhibitory.Neurons" = "darkslategray3"),
                  "Dataset" = c("geo" = "firebrick3", "gse" = "goldenrod3"))

anno <- HeatmapAnnotation(df = met, show_annotation_name = FALSE, col = anno_cols,
                          annotation_legend_param = list(Dataset = list(direction = "horizontal", labels_gp = gpar(fontface = "bold")),
                                                         Receiver = list(labels = c("Excitatory Neurons", "Inhibitory Neurons"), direction = "horizontal", labels_gp = gpar(fontface = "bold"))))
                            
                          

oligo_matrix <- oligo_matrix[, rownames(met), drop = FALSE]

mat <- as.matrix(oligo_matrix)

Heatmap(mat,
        #top_annotation = anno,
        col = cols,
        show_column_names = FALSE,
        show_row_dend = TRUE,
        show_column_dend = FALSE,
        cluster_columns = FALSE,
        row_title = "Oligodendrocyte Ligands",
        row_title_gp = gpar(fontface = "bold"),
        row_names_gp = gpar(fontface = "bold"),
        heatmap_legend_param = list(direction = "horizontal", title = "Pseudobulk Expression",
                                    labels_gp = gpar(fontface = "bold")))
```

# opcs heatmap
```{r}
opc_matrix <- dcast(ligands_opcs, ligand ~ receiver + dataset, value.var = "lfc_ligand") %>%
  column_to_rownames("ligand")

opc_matrix[is.na(opc_matrix)] <- 0

# prep anno
meta <- as.data.frame(colnames(opc_matrix))
rownames(meta) <- meta$`colnames(opc_matrix)`

Receiver <- c("Excitatory.Neurons", "Excitatory.Neurons", "Inhibitory.Neurons", "Inhibitory.Neurons")
Dataset <- c("geo", "gse", "geo", "gse")
met <- cbind(Dataset, Receiver)
rownames(met) <- rownames(meta)
met <- as.data.frame(met)

anno_cols <- list("Receiver" = c("Excitatory.Neurons" = "slateblue3",
                                 "Inhibitory.Neurons" = "darkslategray3"),
                  "Dataset" = c("geo" = "firebrick3", "gse" = "goldenrod3"))

anno <- HeatmapAnnotation(df = met, show_annotation_name = FALSE, col = anno_cols,
                          annotation_legend_param = list(Dataset = list(direction = "horizontal", labels_gp = gpar(fontface = "bold")),
                                                         Receiver = list(labels = c("Excitatory Neurons", "Inhibitory Neurons"), direction = "horizontal", labels_gp = gpar(fontface = "bold"))))
                            
                          

opc_matrix <- opc_matrix[, rownames(met), drop = FALSE]

mat <- as.matrix(opc_matrix)

Heatmap(mat,
        top_annotation = anno,
        col = cols,
        show_column_names = FALSE,
        show_row_dend = TRUE,
        show_column_dend = FALSE,
        cluster_columns = FALSE,
        cluster_rows = TRUE,
        row_title = "OPC Ligands",
        row_title_gp = gpar(fontface = "bold"),
        row_names_gp = gpar(fontface = "bold"),
        heatmap_legend_param = list(direction = "horizontal", title = "Pseudobulk Expression",
                                    labels_gp = gpar(fontface = "bold")))
```
