---
title: "multiNicheNet_geo_gse_overlap"
author: "Tabea M. Soelter"
date: '2023-07-27'
output: html_document
---
### testing geo and gse overlap
```{r}
# load in multinichenet outputs from  gse
output <- readRDS(here("data", "ccc", "gse_multinichenet_output.rds"))

# pull out ligands, receptors, and targets from the cor outputs 

# prep gse multinichenet output for comparison
top_n_target <- 250

group_oi = "AD"
receiver_oi = c("Excitatory.Neurons", "Inhibitory.Neurons")
sender_oi <- c("Astrocytes", "Microglia", "OPCs", "Oligodendrocytes")

contrast_tbl <- tibble(contrast = c("AD-CTRL", "CTRL-AD"),
                       group = c("AD", "CTRL"))

lr_target_prior_cor_filtered = output$lr_target_prior_cor %>%
  inner_join(output$ligand_activities_targets_DEgenes$ligand_activities %>%
               distinct(ligand, target, direction_regulation, contrast)) %>%
  inner_join(contrast_tbl) %>%
  filter(group == group_oi, receiver %in% receiver_oi, sender %in% sender_oi)

lr_target_prior_cor_filtered_up = lr_target_prior_cor_filtered %>%
  filter(direction_regulation == "up") %>%
  filter( (rank_of_target < top_n_target) & (pearson > 0.50 | spearman > 0.50))

lr_target_prior_cor_filtered_down = lr_target_prior_cor_filtered %>%
  filter(direction_regulation == "down") %>%
  filter( (rank_of_target < top_n_target) & (pearson < -0.50 | spearman < -0.50))

lr_target_prior_cor_filtered = bind_rows(lr_target_prior_cor_filtered_up, lr_target_prior_cor_filtered_down)

# Create new column with ligand-receptor-target only info
lr_target_prior_cor_filtered$ligand_receptor_target <- gsub("(_[^_]+_)(.*?)(_[^_]+_)",
                                                            "\\1\\4",
                                                            lr_target_prior_cor_filtered$id_target,
                                                            perl = TRUE)

# Create new column with ligand-receptor only info
lr_target_prior_cor_filtered$ligand_receptor <- gsub("^([^_]*_[^_]*).*",
                                                     "\\1",
                                                     lr_target_prior_cor_filtered$id,
                                                     perl = TRUE)

# Rename receiver cell types
lr_target_prior_cor_filtered$receiver <- ifelse(
  lr_target_prior_cor_filtered$receiver == "Inhibitory.Neurons",
  "Inhibitory Neurons",
  "Excitatory Neurons")

# Check receivers were renamed and number
table(lr_target_prior_cor_filtered$receiver) # 77 152

lr_target_prior_cor_filtered_gse <- lr_target_prior_cor_filtered
```

# prep geo object
```{r}
output <- readRDS(here("data", "ccc", "geo_multinichenet_output.rds"))

top_n_target <- 250

group_oi = "AD"
receiver_oi = c("Excitatory.Neurons", "Inhibitory.Neurons")
sender_oi <- c("Astrocytes", "Microglia", "OPCs", "Oligodendrocytes")

contrast_tbl <- tibble(contrast = c("AD-CTRL", "CTRL-AD"),
                       group = c("AD", "CTRL"))

lr_target_prior_cor_filtered = output$lr_target_prior_cor %>%
  inner_join(output$ligand_activities_targets_DEgenes$ligand_activities %>%
               distinct(ligand, target, direction_regulation, contrast)) %>%
  inner_join(contrast_tbl) %>%
  filter(group == group_oi, receiver %in% receiver_oi, sender %in% sender_oi)

lr_target_prior_cor_filtered_up = lr_target_prior_cor_filtered %>%
  filter(direction_regulation == "up") %>%
  filter( (rank_of_target < top_n_target) & (pearson > 0.50 | spearman > 0.50))

lr_target_prior_cor_filtered_down = lr_target_prior_cor_filtered %>%
  filter(direction_regulation == "down") %>%
  filter( (rank_of_target < top_n_target) & (pearson < -0.50 | spearman < -0.50))

lr_target_prior_cor_filtered = bind_rows(lr_target_prior_cor_filtered_up, lr_target_prior_cor_filtered_down)

# Create new column with ligand-receptor-target only info
lr_target_prior_cor_filtered$ligand_receptor_target <- gsub("(_[^_]+_)(.*?)(_[^_]+_)",
                                                            "\\1\\4",
                                                            lr_target_prior_cor_filtered$id_target,
                                                            perl = TRUE)

# Create new column with ligand-receptor only info
lr_target_prior_cor_filtered$ligand_receptor <- gsub("^([^_]*_[^_]*).*",
                                                     "\\1",
                                                     lr_target_prior_cor_filtered$id,
                                                     perl = TRUE)

# Rename receiver cell types
lr_target_prior_cor_filtered$receiver <- ifelse(
  lr_target_prior_cor_filtered$receiver == "Inhibitory.Neurons",
  "Inhibitory Neurons",
  "Excitatory Neurons")

# Check receivers were renamed and number
table(lr_target_prior_cor_filtered$receiver) # 263 313

lr_target_prior_cor_filtered_geo <- lr_target_prior_cor_filtered
```

# compare overlap
```{r}
geo_ligands <- lr_target_prior_cor_filtered_geo$ligand %>% unique()

gse_ligands <- lr_target_prior_cor_filtered_gse$ligand %>% unique()

i1 <- intersect(geo_ligands, gse_ligands)

length(i1)

geo_receptors <- lr_target_prior_cor_filtered_geo$receptor %>% unique()

gse_receptors <- lr_target_prior_cor_filtered_gse$receptor %>% unique()

i2 <- intersect(geo_receptors, gse_receptors)

length(i2)

geo_targets <- lr_target_prior_cor_filtered_geo$target %>% unique()

gse_targets <- lr_target_prior_cor_filtered_gse$target %>% unique()

i3 <- intersect(geo_targets, gse_targets)

length(i3)


#### 

geo_id <- lr_target_prior_cor_filtered_geo$id %>% unique()

gse_id <- lr_target_prior_cor_filtered_gse$id %>% unique()

i4 <- intersect(geo_id, gse_id)

length(i4)

####
geo_id_target <- lr_target_prior_cor_filtered_geo$id_target %>% unique()

gse_id_target <- lr_target_prior_cor_filtered_gse$id_target %>% unique()

i5 <- intersect(geo_id_target, gse_id_target)

length(i5)

n <- max(length(geo_id), length(gse_id))
length(geo_id) <- n
length(gse_id) <- n

bound <- data.frame(geo_id, gse_id)

bound_ls <- as.list(bound)

bound_lst <- lapply(bound_ls, function(x) x[!is.na(x)])


library(UpSetR)
upset(fromList(bound_lst),
              sets = c("geo_id", "gse_id"),
              order.by = "freq")
```


# pull out overlaps
```{r}
# overlapping ligand-receptor pairs
df <- as.data.frame(i4)

# pull out all l-r-t pairsings for geo
df_geo <- as.data.frame(geo_id_target)

df_geo$id <- gsub("^([^_]*_[^_]*_[^_]*_[^_]*).*",
                      "\\1\\2",
                      df_geo$geo_id_target,
                      perl = TRUE)

df_geo$target <- sub("^(?:[^_]*_){4}(.*)$",
                      "\\1",
                      df_geo$geo_id_target,
                      perl = TRUE)

df_geo_filt <- df_geo %>% filter(id %in% df$i4)


# pull out all l-r-t pairsings for gse
df_gse <- as.data.frame(gse_id_target)

df_gse$id <- gsub("^([^_]*_[^_]*_[^_]*_[^_]*).*",
                      "\\1\\2",
                      df_gse$gse_id_target,
                      perl = TRUE)

df_gse$target <- sub("^(?:[^_]*_){4}(.*)$",
                      "\\1",
                      df_gse$gse_id_target,
                      perl = TRUE)

df_gse_filt <- df_gse %>% filter(id %in% df$i4)
```







